openapi: 3.1.0
info:
  title: Lyric Meaning Explanation API
  description: Lyric Meaning Explanation API provides explanations for song lyrics.
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/v1/api'
paths:
  /users/register:
    post:
      summary: for use registration
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegistration"
      responses:
        "201":
          description: successful registration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
  /users/login:
    post:
      summary: for use login
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLogin"
      responses:
        "200":
          description: successful login
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
  /playlist:
    post:
      summary: create user playlist
      tags:
        - Playlists
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PlaylistRequest"
      responses:
        "200":
          description: successful playlist creation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlaylistCreatedResponse"
    get:
      summary: get all user playlists
      tags:
        - Playlists
      security:
        - bearerAuth: []
      responses:
        "200":
          description: successful playlist creation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlaylistAllResponse"
  /playlist/{id}:
    get:
      summary: get data of a user playlist by id
      tags:
        - Playlists
      security:
        - bearerAuth: []
      responses:
        "200":
          description: successful retrieval of playlist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DetailPlaylistResponse"
  /playlist/{id}/songs:
    post:
      summary: add song to user playlist
      tags:
        - Playlists
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SongRequest"
      responses:
        "201":
          description: successful song addition
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SongAddedResponse"
  /history:
    get:
      summary: get all history based on user
      tags:
        - History
      security:
        - bearerAuth: []
      responses:
        "200":
          description: successful history retrieval
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserHistoryResponse"
    post:
      summary: create history based on user
      tags:
        - History
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserHistoryRequest"
      responses:
        "201":
          description: successful history creation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserHistoryResponse"
components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes
  schemas:
    UserRegistration:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
    UserLogin:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    UserResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
            username:
              type: string
            email:
              type: string
            token:
              type: string
    PlaylistRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
    PlaylistCreatedResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: number
            title:
              type: string
            description:
              type: string
    PlaylistAllResponse:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: number
              title:
                type: string
              description:
                type: string
    SongRequest:
      type: object
      properties:
        title:
          type: string
        artist:
          type: string
        language_code:
          type: string
    SongAddedResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: number
            title:
              type: string
            artist:
              type: string
            language_code:
              type: string
    DetailPlaylistResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: number
            title:
              type: string
            description:
              type: string
            songs:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: number
                  title:
                    type: string
                  artist:
                    type: string
                  language_code:
                    type: string
    UserHistoryResponse:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: number
              song_title:
                type: string
              song_description:
                type: string
              language_code:
                type: string
              interpretation:
                type: string
              emotion:
                type: array
                items:
                  type: string
    UserHistoryRequest:
      type: object
      properties:
        song_title:
          type: string
        song_artist:
          type: string
        language_code:
          type: string
        interpretation:
          type: string
        emotion:
          type: array
          items:
            type: string
